In [22]:
#Author: Tian Zhaoxu
from basic import *
from main import *

In [2]:
multiple = [[12,18,8],[12,6,4]]

In [3]:
X_train = []
for i in range(31):
    for j in range(multiple[0][0]):
        for p in range(multiple[0][1]):
            for q in range(multiple[0][2]):
                index = i*100000 + j*1000 + p*10 + q
                train_path = os.path.join(PROCESSED_DATA_PATH, "train")
                dataframe = load_data(str(index), train_path, skip_rows=False)
                X_train.append(turn_to_1D(dataframe))
X_train = np.array(X_train)
X_train.reshape(31*multiple[0][0]*multiple[0][1]*multiple[0][2], -1)

y_train = []
for i in range(31):
    for j in range(multiple[0][0]):
        for p in range(multiple[0][1]):
            for q in range(multiple[0][2]):
                y_train.append(int(i/8))
y_train = np.array(y_train)
y_train.reshape(1, -1)

X_test = []
for i in range(31):
    for j in range(multiple[1][0]):
        for p in range(multiple[1][1]):
            for q in range(multiple[1][2]):
                index = i*100000 + j*1000 + p*10 + q
                test_path = os.path.join(PROCESSED_DATA_PATH, "test")
                dataframe = load_data(str(index), test_path, skip_rows=False)
                X_test.append(turn_to_1D(dataframe))
X_test = np.array(X_test)
X_test.reshape(31*multiple[1][0]*multiple[1][1]*multiple[1][2], -1)

y_test = []
for i in range(31):
    for j in range(multiple[1][0]):
        for p in range(multiple[1][1]):
            for q in range(multiple[1][2]):
                y_test.append(int(i/8))
y_test = np.array(y_test)
y_test.reshape(1, -1)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(53568, 768)
(53568,)
(8928, 768)
(8928,)


In [4]:
shuffle_index = np.random.permutation(31*multiple[0][0]*multiple[0][1]*multiple[0][2])
X_train, y_train = X_train[shuffle_index], y_train[shuffle_index]
shuffle_index = np.random.permutation(31*multiple[1][0]*multiple[1][1]*multiple[1][2])
X_test, y_test = X_test[shuffle_index], y_test[shuffle_index]

In [5]:
from sklearn.ensemble import RandomForestClassifier
import joblib
from sklearn.model_selection import cross_val_score

In [6]:
rf_clf_5 = RandomForestClassifier(n_estimators=5)
rf_clf_10 = RandomForestClassifier(n_estimators=10)
rf_clf_20 = RandomForestClassifier(n_estimators=20)
rf_clf_40 = RandomForestClassifier(n_estimators=40)
rf_clf_80 = RandomForestClassifier(n_estimators=80)

In [7]:
cross_val_score(rf_clf_5, X_train, y_train, cv=5, scoring="accuracy")

array([0.95146537, 0.96453239, 0.96761247, 0.95342108, 0.94558014])

In [18]:
cross_val_score(rf_clf_10, X_train, y_train, cv=5, scoring="accuracy")

array([0.9838529 , 0.98394624, 0.98179951, 0.98291795, 0.97965089])

In [19]:
cross_val_score(rf_clf_20, X_train, y_train, cv=5, scoring="accuracy")

array([0.99197312, 0.99346649, 0.9924398 , 0.99094558, 0.99234575])

In [20]:
cross_val_score(rf_clf_40, X_train, y_train, cv=5, scoring="accuracy")

array([0.99533321, 0.99467986, 0.99561322, 0.99598619, 0.99598619])

In [16]:
cross_val_score(rf_clf_80, X_train, y_train, cv=5, scoring="accuracy")

array([0.99691992, 0.99579989, 0.9973866 , 0.99607953, 0.99635956])

In [24]:
np.mean([0.95146537, 0.96453239, 0.96761247, 0.95342108, 0.94558014])

0.95652229

In [25]:
np.mean([0.9838529 , 0.98394624, 0.98179951, 0.98291795, 0.97965089])

0.982433498

In [26]:
np.mean([0.99197312, 0.99346649, 0.9924398 , 0.99094558, 0.99234575])

0.992234148

In [27]:
np.mean([0.99533321, 0.99467986, 0.99561322, 0.99598619, 0.99598619])

0.9955197339999999

In [28]:
np.mean([0.99691992, 0.99579989, 0.9973866 , 0.99607953, 0.99635956])

0.9965091000000001