In [1]:
#Author: Tian Zhaoxu
from basic import *
from main import *

In [2]:
multiple = [[18,18,8],[18,6,4]]

In [3]:
X_train = []
for i in range(31):
    for j in range(multiple[0][0]):
        for p in range(multiple[0][1]):
            for q in range(multiple[0][2]):
                index = i*100000 + j*1000 + p*10 + q
                train_path = os.path.join(PROCESSED_DATA_PATH, "train")
                dataframe = load_data(str(index), train_path, skip_rows=False)
                X_train.append(turn_to_1D(dataframe))
X_train = np.array(X_train)
X_train.reshape(31*multiple[0][0]*multiple[0][1]*multiple[0][2], -1)

y_train = []
for i in range(31):
    for j in range(multiple[0][0]):
        for p in range(multiple[0][1]):
            for q in range(multiple[0][2]):
                y_train.append(int(i/8))
y_train = np.array(y_train)
y_train.reshape(1, -1)

X_test = []
for i in range(31):
    for j in range(multiple[1][0]):
        for p in range(multiple[1][1]):
            for q in range(multiple[1][2]):
                index = i*100000 + j*1000 + p*10 + q
                test_path = os.path.join(PROCESSED_DATA_PATH, "test")
                dataframe = load_data(str(index), test_path, skip_rows=False)
                X_test.append(turn_to_1D(dataframe))
X_test = np.array(X_test)
X_test.reshape(31*multiple[1][0]*multiple[1][1]*multiple[1][2], -1)

y_test = []
for i in range(31):
    for j in range(multiple[1][0]):
        for p in range(multiple[1][1]):
            for q in range(multiple[1][2]):
                y_test.append(int(i/8))
y_test = np.array(y_test)
y_test.reshape(1, -1)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(80352, 768)
(80352,)
(13392, 768)
(13392,)


In [4]:
shuffle_index = np.random.permutation(31*multiple[0][0]*multiple[0][1]*multiple[0][2])
X_train, y_train = X_train[shuffle_index], y_train[shuffle_index]
shuffle_index = np.random.permutation(31*multiple[1][0]*multiple[1][1]*multiple[1][2])
X_test, y_test = X_test[shuffle_index], y_test[shuffle_index]

In [5]:
sample_data = X_test[100]
sample_label = y_test[100]
sample_label

0

In [6]:
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC

import joblib

In [7]:
sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train,y_train)
joblib.dump(sgd_clf, "models/sgd_clf.pkl")

['models/sgd_clf.pkl']

In [8]:
kn_clf = KNeighborsClassifier()
kn_clf.fit(X_train, y_train)
joblib.dump(kn_clf, "models/kn_clf.pkl")

['models/kn_clf.pkl']

In [9]:
dt_clf = tree.DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)
joblib.dump(dt_clf, "models/dt_clf.pkl")

['models/dt_clf.pkl']

In [10]:
rf_clf = RandomForestClassifier(n_estimators=20)
rf_clf.fit(X_train, y_train)
joblib.dump(rf_clf, "models/rf_clf.pkl")

['models/rf_clf.pkl']

In [11]:
gb_clf = GradientBoostingClassifier(n_estimators=20)
gb_clf.fit(X_train, y_train)
joblib.dump(gb_clf, "models/gb_clf.pkl")

['models/gb_clf.pkl']

In [12]:
svc_clf = SVC(kernel='rbf', probability=True)
svc_clf.fit(X_train, y_train)
joblib.dump(svc_clf, "models/svc_clf.pkl")

['models/svc_clf.pkl']

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
cross_val_score(sgd_clf, X_train, y_train, cv=5, scoring="accuracy")

array([0.99751104, 0.99632879, 0.99533292, 0.99632856, 0.99589297])

In [15]:
cross_val_score(kn_clf, X_train, y_train, cv=5, scoring="accuracy")

array([1.        , 1.        , 0.99993777, 1.        , 0.99993777])

In [16]:
cross_val_score(dt_clf, X_train, y_train, cv=5, scoring="accuracy")

array([0.9598656 , 0.95582104, 0.9542626 , 0.95588052, 0.96795271])

In [17]:
cross_val_score(rf_clf, X_train, y_train, cv=5, scoring="accuracy")

array([0.99178645, 0.98736855, 0.9876789 , 0.98842564, 0.9858743 ])

In [18]:
cross_val_score(gb_clf, X_train, y_train, cv=5, scoring="accuracy")

array([0.89334827, 0.89571277, 0.89508401, 0.89085252, 0.89203485])

In [19]:
cross_val_score(svc_clf, X_train, y_train, cv=5, scoring="accuracy")

array([1., 1., 1., 1., 1.])